Adds calculaiton of fee
skopczynska/spio-to pull request #7
Opened 2022-02-27 11:37 UTC by skopczynska

2023-01-22 10:41 UTC, kpierzynski commented on 01-CodeReviewEx/Shop-Ex/Account.cs
> +        public static const int STANDARD = 0, BUDGET = 1, PREMIUM = 2, PREMIUM_PLUS = 3;
Remove static keyword, since const is static by default

2023-01-23 18:11 UTC, wsz82 requested changes

2023-01-23 18:11 UTC, wsz82 commented on 01-CodeReviewEx/Shop-Ex/Program.cs
> +                if (account.accountType == Account.PREMIUM || account.accountType == Account.PREMIUM_PLUS) totalFee += .0125 * ( // 1.25% broker's fee
Fee calculation can be moved to Account class:

public double calculateFee(double : brokerFee)

2023-01-23 18:11 UTC, wsz82 commented on 01-CodeReviewEx/Shop-Ex/Program.cs
> +                if (account.accountType == Account.PREMIUM || account.accountType == Account.PREMIUM_PLUS) totalFee += .0125 * ( // 1.25% broker's fee
.0125 can be kept in const BROKER_FEE, so you wouldn't need comment here

2023-01-23 18:11 UTC, wsz82 commented on 01-CodeReviewEx/Shop-Ex/Program.cs
> +                if (account.accountType == Account.PREMIUM || account.accountType == Account.PREMIUM_PLUS) totalFee += .0125 * ( // 1.25% broker's fee
You could add code block after if

2023-01-23 18:11 UTC, wsz82 commented on 01-CodeReviewEx/Shop-Ex/Program.cs
> +            for (int i = 0; i < accounts.Length; i++)
This can be moved to for each:
for (account in accounts) {}

2023-01-23 18:11 UTC, wsz82 commented on 01-CodeReviewEx/Shop-Ex/Program.cs
> +            myAccounts[0] = a;
Array size is 10, but only one element is added.

2023-01-23 18:11 UTC, wsz82 commented on 01-CodeReviewEx/Shop-Ex/Program.cs
> +            a = new Account() { principal = 1.5, rate = 0.75 };
This object is not used anywhere.

2023-01-23 18:11 UTC, wsz82 commented on 01-CodeReviewEx/Shop-Ex/Program.cs
> +            Account a = new Account();
Variable name should be meaningful

2023-01-23 18:11 UTC, wsz82 commented on 01-CodeReviewEx/Shop-Ex/Program.cs
> +        public static double calculateFee(Account[] accounts)
The method should be private

2023-11-24 15:38 UTC, closed without merging